### ISSUE TITLE
在Mac端的obs无效

### ISSUE THREAD

**Issue by Lawrenceeeeeeee** [linnaea/rotaeno-stablizer#1]
在Mac端的obs上应用了该插件，但是视频没有转起来
手机是iPhone 14
<img width="863" alt="image" src="https://github.com/linnaea/obs-rotaeno-stablizer/assets/125617257/62aba4a3-fe12-4798-a17b-f47767251d1f">
这边手机已经倾斜了（左下角的色块偏红）但是视频没有旋转
<img width="1465" alt="image" src="https://github.com/linnaea/obs-rotaeno-stablizer/assets/125617257/a3c66ed6-91f0-4f33-9305-886f767c3b42">

**Comment by linnaea** [comment]
OBS好像没翻译`mat2`类型的样子，现在的版本Linux上能跑，Mac应该没问题

**Comment by Lawrenceeeeeeee** [comment]
> OBS好像没翻译`mat2`类型的样子，现在的版本Linux上能跑，Mac应该没问题

现在是能转了，但是转反了啊（
