### ISSUE TITLE
V2旋转滤镜角度错误

### ISSUE THREAD

**Issue by JerryHan3** [linnaea/rotaeno-stablizer#3]
应用最新的滤镜之后整个视频开始乱转。（图为旋转角度错误的一帧，应该能看到四角的色块）
![image](https://github.com/linnaea/obs-rotaeno-stablizer/assets/63506570/cf4140db-d7bf-4a4a-9b03-a9d328a581a3)

**Comment by JerryHan3** [comment]
图中左上角色块为白色，右上角色块为绿色，左下角、右下角色块均为紫色。

**Comment by linnaea** [comment]
OBS滤镜顺序有讲究的，你这个是竖屏状态输入先过了稳定再旋转成横屏的结果

我看看直接集成一个旋转功能得了

**Comment by JerryHan3** [comment]
先把视频用外部工具转过来再拉到OBS里面上滤镜应该就不会出问题了吧

**Comment by JerryHan3** [comment]
现在手动指定旋转方向之后视频就正常了，非常感谢！
